"""cookies_json_to_netscape — convert a browser cookie-export JSON to a Netscape cookies.txt
that yt-dlp / youtube-transcript-api can consume. Contains NO secrets itself; reads a JSON
export file and writes the Netscape file. Both live under data/ (gitignored).

  python scripts/cookies_json_to_netscape.py data/_yt_cookies_raw.json data/yt_cookies.txt
"""
from __future__ import annotations
import json, sys
from pathlib import Path


def convert(src: str, dst: str) -> int:
    data = json.loads(Path(src).read_text(encoding="utf-8"))
    lines = ["# Netscape HTTP Cookie File", "# generated by cookies_json_to_netscape.py", ""]
    n = 0
    for c in data:
        domain = c.get("domain", "")
        if not domain:
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        exp = int(c.get("expirationDate") or 0)
        name = c.get("name", "")
        value = c.get("value", "")
        dom = ("#HttpOnly_" + domain) if c.get("httpOnly") else domain   # yt-dlp honors this prefix
        lines.append("\t".join([dom, include_sub, path, secure, str(exp), name, value]))
        n += 1
    Path(dst).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return n


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else "data/_yt_cookies_raw.json"
    dst = sys.argv[2] if len(sys.argv) > 2 else "data/yt_cookies.txt"
    count = convert(src, dst)
    print(f"wrote {count} cookies -> {dst}")
